steps:
    - name: "ubuntu"
      args: ['ls']
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/crack-atlas-251509/flask", "."]
      dir: 'flask'
    - name: "gcr.io/cloud-builders/docker"
      args: ['push',"gcr.io/crack-atlas-251509/flask"]
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'flask', '--image', 'gcr.io/crack-atlas-251509/flask:latest',
       '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
    - name: "gcr.io/cloud-builders/gcloud"
      args: ["container", "images", "delete", "gcr.io/crack-atlas-251509/flask", "--force-delete-tags"]
    - name: "gcr.io/cloud-builders/gcloud"
      args: ["run", "revisions", "delete", 'flask*',
       '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
