#plz set appname to env "Cloud Build→trigger→env→'_APPNAME'"
#plz set GCP_project_dicetry to env "Cloud Build→trigger→env→'_PROJECT'"

steps:
      #build      
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "$_PROJECT/$_APPNAME", "."]
      dir: '$_APPNAME'
      #test
    - name: "gcr.io/cloud-builders/docker"
      args: ['run','--rm',"$_PROJECT/$_APPNAME","bash"]
      #push image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ['push',"$_PROJECT/$_APPNAME"]
      #deploy
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['beta','run', 'deploy', '$_APPNAME', '--image', '$_PROJECT/$_APPNAME:latest',
       '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
      #delete image from Container Registry
#    - name: "gcr.io/cloud-builders/gcloud"
#      args: ["container", "images", "delete", "$_PROJECT/$_APPNAME", "--force-delete-tags"]
      #delete past revisions
#    - name: "$_PROJECT/gcloud"
#      args: ['beta',"run", "revisions", "delete", 'flask-^',
#       '--region', 'us-central1', '--platform', 'managed',"--quiet"]
