steps:
    - name: "gcr.io/cloud-builders/docker"
      args: ['exec -i ubuntu /bin/bash -c "cd flask"']

    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/crack-atlas-251509/flask:latest", "."]
    - name: "gcr.io/cloud-builders/gcloud"
      args: ["docker -- push gcr.io/crack-atlas-251509/flask"]


