steps:
    - name: "ubuntu"
      args: ['ls']
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/crack-atlas-251509/flask:latest", "."]
      dir: 'flask'
images: ['gcr.io/crack-atlas-251509/flask']

steps:
    - name: "gcr.io/cloud-builders/gcloud"
      args: ["container images delete gcr.io/crack-atlas-251509/flask --force-delete-tags"]


